
set(CMAKE_SYSTEM_NAME Linux)
set(EGCS TRUE)
set(LINUX TRUE)

set(CMAKE_C_COMPILER "gcc.cmd")
set(CMAKE_CXX_COMPILER "g++.cmd")
set(CMAKE_AR "ar.cmd" CACHE INTERNAL "")
set(CMAKE_RANLIB "ranlib.cmd" CACHE INTERNAL "")

set(CMAKE_C_COMPILER_ID "GNU")
set(CMAKE_CXX_COMPILER_ID "GNU")
set(CMAKE_C_COMPILER_VERSION "2.8.1")
set(CMAKE_CXX_COMPILER_VERSION "2.8.1")

set(CMAKE_SKIP_COMPILER_CHECK TRUE)
set(CMAKE_C_COMPILER_ID_RUN TRUE)
set(CMAKE_CXX_COMPILER_ID_RUN TRUE)
set(CMAKE_C_ABI_COMPILED TRUE)
set(CMAKE_CXX_ABI_COMPILED TRUE)
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)
